### ISSUE TITLE
shader error,my editor is 2022.2.2f1

### ISSUE THREAD

**Issue by gdtiti** [creativeIKEP/BlazePoseBarracuda#10]
WindowsVideoMedia error unhandled Color Standard: 0  falling back to default this may result in rendering issues

Process.compute: Kernel at index (0) is invalid
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Mediapipe.BlazePose.BlazePoseDetecter:ProcessImage (UnityEngine.Texture,Mediapipe.BlazePose.BlazePoseModel,single,single) (at Packages/BlazePoseBarracuda/Script/BlazePoseDetecter.cs:108)
PoseVisuallizer3D:LateUpdate () (at Assets/Script/PoseVisuallizer3D.cs:48)

IndexOutOfRangeException: Invalid kernelIndex (1) passed, must be non-negative less than 6.
Unity.Barracuda.ComputeFunc..ctor (Unity.Barracuda.ComputeShaderContext ctx, System.String kn) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:2653)
Unity.Barracuda.ComputeKernel.CalculateEntryScore (Unity.Barracuda.ComputeShaderContext ctx, Unity.Barracuda.ComputeKernelLibrary+Entry entry, System.Boolean verbose) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:915)
Unity.Barracuda.ComputeKernel.BestKernel (Unity.Barracuda.ComputeShaderContext ctx, System.Collections.Generic.List`1[T] entrees, System.Boolean verbose) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:960)
Unity.Barracuda.ComputeOps.BestKernel (System.Collections.Generic.List`1[T] entrees) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:1028)
Unity.Barracuda.PrecompiledComputeOps.PrepareModel (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/BarracudaPrecompiledCompute.cs:302)
Unity.Barracuda.StatsOps.PrepareModel (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/StatsOps.cs:51)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__33.MoveNext () (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/GenericWorker.cs:214)
Unity.Barracuda.GenericWorker.Execute () (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/GenericWorker.cs:160)
Unity.Barracuda.GenericWorker.Execute (Unity.Barracuda.Tensor input) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Backends/GenericWorker.cs:152)
Mediapipe.PoseDetection.PoseDetecter.ProcessImage (UnityEngine.Texture inputTexture, System.Single poseThreshold, System.Single iouThreshold) (at Library/PackageCache/jp.ikep.mediapipe.posedetection@1.0.0/Script/PoseDetecter.cs:67)
Mediapipe.BlazePose.BlazePoseDetecter.ProcessImage (UnityEngine.Texture inputTexture, Mediapipe.BlazePose.BlazePoseModel blazePoseModel, System.Single poseThreshold, System.Single iouThreshold) (at Packages/Blaz

**Comment by VimalMollyn** [comment]
Same, but with 2020.3.30f1. Exact error is:

```
Postprocess.compute: Kernel at index (0) is invalid
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Mediapipe.PoseDetection.PoseDetecter:ProcessImage (UnityEngine.ComputeBuffer,single,single) (at Library/PackageCache/jp.ikep.mediapipe.posedetection@21c7f98642/Script/PoseDetecter.cs:83)
Mediapipe.BlazePose.BlazePoseDetecter:ProcessImage (UnityEngine.Texture,Mediapipe.BlazePose.BlazePoseModel,single,single) (at Packages/BlazePoseBarracuda/Script/BlazePoseDetecter.cs:117)
PoseVisuallizer:LateUpdate () (at Assets/Script/PoseVisuallizer.cs:40)

Shader error in 'Postprocess': Couldn't open include file 'Common.cginc'. at kernel PostprocessFor16Map at BlazePoseBarracuda/Library/PackageCache/jp.ikep.mediapipe.posedetection@1.0.1/ComputeShader/Postprocess.compute(18)

Shader error in 'Postprocess': Couldn't open include file 'Common.cginc'. at kernel PostprocessFor8Map at BlazePoseBarracuda/Library/PackageCache/jp.ikep.mediapipe.posedetection@1.0.1/ComputeShader/Postprocess.compute(18)

Shader error in 'Postprocess': Couldn't open include file 'Common.cginc'. at kernel PostprocessFor16Map at Postprocess.compute(18)

Shader error in 'Postprocess': Couldn't open include file 'Common.cginc'. at kernel PostprocessFor8Map at Postprocess.compute(18)

Postprocess.compute: Kernel at index (1) is invalid
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Mediapipe.PoseDetection.PoseDetecter:ProcessImage (UnityEngine.ComputeBuffer,single,single) (at Library/PackageCache/jp.ikep.mediapipe.posedetection@21c7f98642/Script/PoseDetecter.cs:89)
Mediapipe.BlazePose.BlazePoseDetecter:ProcessImage (UnityEngine.Texture,Mediapipe.BlazePose.BlazePoseModel,single,single) (at Packages/BlazePoseBarracuda/Script/BlazePoseDetecter.cs:117)
PoseVisuallizer:LateUpdate () (at Assets/Script/PoseVisuallizer.cs:40)

Shader error in 'PostProcess2': Couldn't open include file 'Common.cginc'. at kernel PostProcess2 at BlazePoseBarracuda/Library/PackageCache/jp.ikep.mediapipe.posedetection@1.0.1/ComputeShader/PostProcess2.compute(2)

Shader error in 'PostProcess2': Couldn't open include file 'Common.cginc'. at kernel PostProcess2 at PostProcess2.compute(2)

PostProcess2.compute: Kernel at index (0) is invalid
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Mediapipe.PoseDetection.PoseDetecter:ProcessImage (UnityEngine.ComputeBuffer,single,single) (at Library/PackageCache/jp.ikep.mediapipe.posedetection@21c7f98642/Script/PoseDetecter.cs:100)
Mediapipe.BlazePose.BlazePoseDetecter:ProcessImage (UnityEngine.Texture,Mediapipe.BlazePose.BlazePoseModel,single,single) (at Packages/BlazePoseBarracuda/Script/BlazePoseDetecter.cs:117)
PoseVisuallizer:LateUpdate () (at Assets/Script/PoseVisuallizer.cs:40)

```

**Comment by creativeIKEP** [comment]
@gdtiti @VimalMollyn 
The error does not occur in my environment, so please tell me how to reproduce it.

**Comment by creativeIKEP** [comment]
I believe this issue is resolved.
I close this issue.
