### ISSUE TITLE
3D Avatar Animation

### ISSUE THREAD

**Issue by hshreeshail** [creativeIKEP/BlazePoseBarracuda#13]
Does the code have functionality to perform 3D avatar animation (like [this](https://www.youtube.com/watch?v=K-_krrs05qw))? I only see landmark points being animated (stick figure style) in the GitHub page.

**Comment by creativeIKEP** [comment]
Hello, @Shreeshail-Hingane .
This repository does not contain 3D avatar animation sorce code.
However, I am planing to develop the avatar animation softwere. ( #2 )
Thanks.

**Comment by creativeIKEP** [comment]
I have released an application that moves avatars. Please try using it.
https://github.com/creativeIKEP/HolisticMotionCapture
