### ISSUE TITLE
Detecter returns NaN for x,y,z in each (x, y, z, w) Pose World Landmark

### ISSUE THREAD

**Issue by deeptronos** [creativeIKEP/BlazePoseBarracuda#15]
Hi there!

BlazePose runs just fine in the Unity Project from this repository on my computer. I'm trying to integrate BlazePoseBarracuda into a different Unity Project, but I'm experiencing odd behavior from the PoseVisualizer/PoseVisualizer3D scripts in that project.

I've exported all of the assets from this original Unity Project as a ```.unitypackage``` file. After that, I install the packages required for BlazePoseBarracuda using [this technique in the README](https://github.com/creativeIKEP/BlazePoseBarracuda#install-from-github-url) in the new Project, and there seems to be no problems with that process. Then, I import my BlazePoseBarracuda .unitypackage in the new Project. When I run a demo scene in the new project, e.g. the ```3DSampleScene```, no pose skeleton appears &  the ```Debug.Log()``` calls in ```PoseVisuallizer3d.cs``` output ```Vector4```s of the format ```(NaN, NaN, NaN, w)```, where w is the landmark position visibility score. ```w``` seems to consistently be a number, but the first three coordinates (the x, y, z  of each pose landmark) are NEVER a number. They're only ```NaN```.  The 33rd index data is always consistently (0.0, 0.0, 0.0, 0.0) too.

See the below screenshot for an example (I was visible to the webcam for this capture, so, if BlazePose were working, it would have been able to detect a pose.)
![Screenshot](https://user-images.githubusercontent.com/9434808/180502367-f3bb07ff-dccc-4f35-b9a6-3fb286b982f4.png)

Technical details:
I'm running MacOS 12.3/Unity 2020.3.33f1. I'm using Barracuda 2.1.0-preview (because it's required for another NN pose detection implementation. I've tried other ver of Barracuda with BlazePoseBarracuda in this Unity Project and had same result.)
My build target is Android. My computer has an Intel CPU and an AMD GPU.
Graphics APIs: OpenGLES2 & 3 are enabled, but Metal I think since I'm on a Mac?

**Comment by creativeIKEP** [comment]
@deeptronos 
The Nan phenomenon could not be reproduced in my environment (MacOS 12.5, M1 Max chip MacBook & Barracuda updated to 2.1.0-preview)

**Comment by deeptronos** [comment]
@creativeIKEP 
I believe this error may have something to do with Metal on Intel or AMD hardware... but I also suspect that my package installs are not configured entirely correctly.

**Comment by creativeIKEP** [comment]
@deeptronos
Can you try the following and see if the issue still occurs?
- Delete `Library` directory for script recompile and restart Unity Editor.
- Confirm your project settings of your project are same with project settings of BlazePoseBarracuda, and see if you have similar issues with the same project settings.

Supplement:
You have a project for OpenGL ES on Android as your build target, but Unity Barracuda's GPU inference does [not support OpenGL ES on Android](https://docs.unity3d.com/Packages/com.unity.barracuda@2.1/manual/SupportedPlatforms.html).

**Comment by creativeIKEP** [comment]
I believe this issue is resolved.
I close this issue.
