### ISSUE TITLE
3D Avatar

### ISSUE THREAD

**Issue by shaunsahdev** [creativeIKEP/BlazePoseBarracuda#19]
Hey, could you give any details for how the landmark data could be mapped to the joint of a rigged avatar? Thanks!

**Comment by creativeIKEP** [comment]
Hello, @shaunsahdev  .
You can refer [kalidokit](https://github.com/yeemachine/kalidokit) .
Also, I am planing to develop the avatar animation softwere. ( https://github.com/creativeIKEP/BlazePoseBarracuda/issues/2 , https://github.com/creativeIKEP/BlazePoseBarracuda/issues/13 )
Thanks.

**Comment by creativeIKEP** [comment]
I have released an application that moves avatars. Please try using it.
https://github.com/creativeIKEP/HolisticMotionCapture

**Comment by shaunsahdev** [comment]
Hey @creativeIKEP, only just saw this but looks just like what I'm after, thanks!
