### ISSUE TITLE
demo with unity chan avatar

### ISSUE THREAD

**Issue by ghost** [creativeIKEP/BlazePoseBarracuda#2]
Hi @creativeIKEP ,

Hope you are all well !

I was wondering if it would be possible to add a scene with the Unity Chan avatar as a demo ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by creativeIKEP** [comment]
Hi, @lucmichalski 
I'm condering same and I had same idea.
In the future, I may add the demo...
Thanks.

**Comment by creativeIKEP** [comment]
I have released an application that moves avatars. Please try using it.
https://github.com/creativeIKEP/HolisticMotionCapture
