### ISSUE TITLE
Get landmark screen position

### ISSUE THREAD

**Issue by kexar** [creativeIKEP/BlazePoseBarracuda#3]
Hi, is it possible to get a landmark screen position in C# script? Thanks

**Comment by creativeIKEP** [comment]
Hi, @kexar  .
BlazePoseBarracuda output screen landmarks in the GPU memory([ComputeBuffer](https://docs.unity3d.com/ScriptReference/ComputeBuffer.html)), but you can transfer to CPU memory with [ComputeBuffer.GetData](https://docs.unity3d.com/ScriptReference/ComputeBuffer.GetData.html) method.
You can get landmarks in C# script if you use ComputeBuffer.GetData method.
Please check `Usage Demo` in [README.md](https://github.com/creativeIKEP/BlazePoseBarracuda/blob/main/README.md) .
