### ISSUE TITLE
CPU vs GPU Inference

### ISSUE THREAD

**Issue by BlueprintBen** [creativeIKEP/BlazePoseBarracuda#6]
Thanks for the project - love keijiro's work and seeing more in its spirit!

I was hoping for confirmation on which in this set of models are running on the CPU vs the GPU and what the path would look like to achieve inference purely on the GPU if not already there. I can see a heavy load on the CPU and so am unable to hit 30fps in testing (even on PC) so am curious if it'll be achievable in the future (by myself or others).

Cheers

**Comment by creativeIKEP** [comment]
Hello, @BlueprintBen !

Currently, BlazePoseBarracuda is optimized for GPU inference.
In my environment, BlazePoseBarracuda is running at about 200 FPS or more performance on the high performance GPU (ex: RTX2080 super).
On the other hand, BlazePoseBarracuda is running at about 20 FPS or less performance on the not high performance computer (ex: Macbook Pro Early 2015).
Thus, depending on the GPU performance of the computer, there are cases where real-time operation is difficult.

Thanks.

**Comment by BlueprintBen** [comment]
Is there anything that I have to enable in the example scene to utilize the GPU rather than the CPU? I have an RTX 6000 but am seeing almost 30ms of Barracuda.Execute.

![image (8)](https://user-images.githubusercontent.com/26749774/140535125-53508bf7-39b4-41f6-a090-f1e379fd4d3d.png)

**Comment by creativeIKEP** [comment]
FPS drops when using Deep Profile not only in Standalone build but also in Unity Editor.
Therefore, try to check the FPS from the Stats in the Game Window without using the Deep Profile.

Also, in PoseDetectionBarracuda and PoseLandmarkBarracuda, the device used for inference is not explicitly specified, but is automatically set by Unity Barracuda.
Therefore, can you please clone PoseDetectionBarracuda and PoseLandmarkBarracuda to your local PC and explicitly specify GPU inference?
The changes in the source code are as follows.
Change lines:

- https://github.com/creativeIKEP/PoseDetectionBarracuda/blob/33279c9945e16244a62edcdc8804ee284f58e3af/Packages/PoseDetectionBarracuda/Script/PoseDetecter.cs#L44
- https://github.com/creativeIKEP/PoseLandmarkBarracuda/blob/e57ab453b61efebdadeb94589a13336734f78af2/Packages/PoseLandmarkBarracuda/Script/PoseLandmarker.cs#L152

Code change:
```
woker = model.CreateWorker();
```
↓
```
woker = model.CreateWorker(WorkerFactory.Device.GPU);
```

**Comment by BlueprintBen** [comment]
My apologies - I think you're absolutely right that Deep Profiling used with Barracuda produces flawed results and that a non-deep-profiling build appears to match your numbers more closely. Will see if the code change makes a difference but I'm much happier with the performance now.
